### ISSUE TITLE
Wally stops seeing Moonlander intermittently.

### ISSUE THREAD

**Issue by kaosfere** [zsa/wally-win#6]
I'm using the latest stable Wally (3.0.1) on Windows 10 to flash a Moonlander.   It will usually work for several flash cycles, but eventually Wally just seems to lose track of the board and gets stuck on "Looking...".  

The logs say nothing more than:

`11:16:46 - Info - Wally is up to date.
11:16:45 - Info - Checking for updates.
11:16:45 - Info - Starting enumeration, targeting any compatible devices.
11:16:45 - Info - Application started
`

Things that don't work to fix it:

* restarting Wally
* resetting the board
* unplugging and plugging it back in
* removing the USB device in Device Manager

Things that do work:

* rebooting

Additionally, I have found that when it is like this I *can* still use wally-cli successfully, but it finishes with an error:

`Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at CLI.Program.<>c__DisplayClass4_0.<<Main>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Kurukuru.Spinner.<StartAsync>d__51.MoveNext()    
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CLI.Program.<Main>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CLI.Program.<Main>(String[] args)`  

Everything seems to work fine in spite of the error message.

**Comment by kaosfere** [comment]
(I have not tried to use wally-cli when the GUI is working, so I do not know if it emits the same error in that state.  I can check when I'm next able to reboot my system.)
